export const GET_RECIPE_ID = "GET_RECIPE_ID";
export const GET_RECIPE = "GET_RECIPE";
export const CREATE_NEW_RECIPE = "CREATE_NEW_RECIPE";
export const SAVE_RECIPE_NAME = "SAVE_RECIPE_NAME";
export const SAVE_INGREDIENT = "SAVE_INGREDIENT";
export const SAVE_INSTRUCTION_VALUE = "SAVE_INSTRUCTION_VALUE";
export const SAVE_INSTRUCTION_NUMBER = "SAVE_INSTRUCTION_NUMBER";